-- AlterTable
ALTER TABLE `McuResult` ADD COLUMN `pemeriksaanAudiometryPetugas` VARCHAR(191) NULL,
    ADD COLUMN `pemeriksaanAudiometryStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `pemeriksaanEkgPetugas` VARCHAR(191) NULL,
    ADD COLUMN `pemeriksaanEkgStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `pemeriksaanFisikForm` JSON NULL,
    ADD COLUMN `pemeriksaanLabPetugas` VARCHAR(191) NULL,
    ADD COLUMN `pemeriksaanLabStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `pemeriksaanRadiologiPetugas` VARCHAR(191) NULL,
    ADD COLUMN `pemeriksaanRadiologiStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `pemeriksaanSpirometryPetugas` VARCHAR(191) NULL,
    ADD COLUMN `pemeriksaanSpirometryStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `pemeriksaanTreadmillPetugas` VARCHAR(191) NULL,
    ADD COLUMN `pemeriksaanTreadmillStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `pemeriksaanUrinPetugas` VARCHAR(191) NULL,
    ADD COLUMN `pemeriksaanUrinStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING';
