-- CreateTable
CREATE TABLE `Company` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `address` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Company_id_key`(`id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fullName` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `roleId` INTEGER NOT NULL,
    `companyId` VARCHAR(191) NULL,

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Role` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Role_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Patient` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `patientId` VARCHAR(191) NOT NULL,
    `fullName` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NULL,
    `dob` DATETIME(3) NOT NULL,
    `age` INTEGER NOT NULL,
    `gender` VARCHAR(191) NOT NULL,
    `position` VARCHAR(191) NOT NULL,
    `division` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NOT NULL,
    `location` VARCHAR(191) NOT NULL,
    `department` VARCHAR(191) NOT NULL,
    `address` TEXT NULL,
    `phoneNumber` VARCHAR(191) NULL,
    `qrCode` VARCHAR(191) NOT NULL,
    `mcuPackage` JSON NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `companyId` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Patient_patientId_key`(`patientId`),
    UNIQUE INDEX `Patient_qrCode_key`(`qrCode`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `McuResult` (
    `id` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'IN_PROGRESS',
    `patientId` INTEGER NOT NULL,
    `healthHistoryAnswers` JSON NULL,
    `dassTestAnswers` JSON NULL,
    `fasTestAnswers` JSON NULL,
    `formSubmittedAt` DATETIME(3) NULL,
    `beratBadan` DOUBLE NULL,
    `tinggiBadan` DOUBLE NULL,
    `bmi` TEXT NULL,
    `lingkarPerut` TEXT NULL,
    `tekananDarah` TEXT NULL,
    `nadi` TEXT NULL,
    `suhu` TEXT NULL,
    `pernafasan` TEXT NULL,
    `fisikKondisiUmum` TEXT NULL,
    `fisikKesadaran` TEXT NULL,
    `fisikKulit` TEXT NULL,
    `fisikKepalaLeher` TEXT NULL,
    `visusOd` TEXT NULL,
    `visusOs` TEXT NULL,
    `butaWarna` TEXT NULL,
    `kacamata` TEXT NULL,
    `kacamataOd` TEXT NULL,
    `kacamataOs` TEXT NULL,
    `lapangPandang` TEXT NULL,
    `fisikMataLainnya` TEXT NULL,
    `fisikTelinga` TEXT NULL,
    `fisikHidung` TEXT NULL,
    `fisikTenggorokan` TEXT NULL,
    `fisikKardiovaskular` TEXT NULL,
    `fisikPernafasan` TEXT NULL,
    `fisikPencernaan` TEXT NULL,
    `fisikEkstremitas` TEXT NULL,
    `hemoglobin` TEXT NULL,
    `leukosit` TEXT NULL,
    `trombosit` TEXT NULL,
    `hematokrit` TEXT NULL,
    `eritrosit` TEXT NULL,
    `led` TEXT NULL,
    `mcv` TEXT NULL,
    `mch` TEXT NULL,
    `mchc` TEXT NULL,
    `rdw` TEXT NULL,
    `mpv` TEXT NULL,
    `pdw` TEXT NULL,
    `hitungJenisEosinofil` TEXT NULL,
    `hitungJenisBasofil` TEXT NULL,
    `hitungJenisNeutrofilStab` TEXT NULL,
    `hitungJenisNeutrofilSegmen` TEXT NULL,
    `hitungJenisLimfosit` TEXT NULL,
    `hitungJenisMonosit` TEXT NULL,
    `gulaDarahPuasa` TEXT NULL,
    `gulaDarah2JamPP` TEXT NULL,
    `sgot` TEXT NULL,
    `sgpt` TEXT NULL,
    `asamUrat` TEXT NULL,
    `kolesterolTotal` TEXT NULL,
    `trigliserida` TEXT NULL,
    `ureum` TEXT NULL,
    `kreatinin` TEXT NULL,
    `hdl` TEXT NULL,
    `ldl` TEXT NULL,
    `hbsag` TEXT NULL,
    `bilirubinTotal` TEXT NULL,
    `bilirubinDirect` TEXT NULL,
    `alkaliPhosphatase` TEXT NULL,
    `urinWarna` TEXT NULL,
    `urinKejernihan` TEXT NULL,
    `urinBau` TEXT NULL,
    `urinPh` TEXT NULL,
    `urinBeratJenis` TEXT NULL,
    `urinProtein` TEXT NULL,
    `urinGlukosa` TEXT NULL,
    `urinBilirubin` TEXT NULL,
    `urinUrobilinogen` TEXT NULL,
    `urinKeton` TEXT NULL,
    `urinNitrit` TEXT NULL,
    `urinLeukositEsterase` TEXT NULL,
    `urinBlood` TEXT NULL,
    `urinSedimenEritrosit` TEXT NULL,
    `urinSedimenLeukosit` TEXT NULL,
    `urinSedimenEpitel` TEXT NULL,
    `urinCaOxalat` TEXT NULL,
    `urinUridAcid` TEXT NULL,
    `urinGranulaCast` TEXT NULL,
    `rontgenImage` TEXT NULL,
    `kesanRontgen` TEXT NULL,
    `kesanUsgAbdomen` TEXT NULL,
    `kesanUsgMammae` TEXT NULL,
    `ekgImage` TEXT NULL,
    `ekgRhythm` TEXT NULL,
    `ekgQrsRate` TEXT NULL,
    `ekgAxis` TEXT NULL,
    `ekgPWave` TEXT NULL,
    `ekgPrInterval` TEXT NULL,
    `ekgQrsDuration` TEXT NULL,
    `ekgQWave` TEXT NULL,
    `ekgTWave` TEXT NULL,
    `ekgStChanges` TEXT NULL,
    `ekgOthers` TEXT NULL,
    `ekgConclusion` TEXT NULL,
    `ekgAdvice` TEXT NULL,
    `audiometriTelingaKanan` TEXT NULL,
    `audiometriTelingaKiri` TEXT NULL,
    `kesimpulanAudiometri` TEXT NULL,
    `spirometriFvc` TEXT NULL,
    `spirometriFev1` TEXT NULL,
    `spirometriFev1Fvc` TEXT NULL,
    `kesimpulanSpirometri` TEXT NULL,
    `usgAbdomenImage1` TEXT NULL,
    `usgAbdomenImage2` TEXT NULL,
    `usgAbdomenImage3` TEXT NULL,
    `usgAbdomenImage4` TEXT NULL,
    `usgAbdomenImage5` TEXT NULL,
    `usgAbdomenImage6` TEXT NULL,
    `usgAbdomenHepar` TEXT NULL,
    `usgAbdomenGallBladder` TEXT NULL,
    `usgAbdomenLien` TEXT NULL,
    `usgAbdomenPancreas` TEXT NULL,
    `usgAbdomenGinjalDekstra` TEXT NULL,
    `usgAbdomenGinjalSinistra` TEXT NULL,
    `usgAbdomenKesimpulan` TEXT NULL,
    `usgMammaeImage1` TEXT NULL,
    `usgMammaeImage2` TEXT NULL,
    `usgMammaeImage3` TEXT NULL,
    `usgMammaeImage4` TEXT NULL,
    `usgMammaeImage5` TEXT NULL,
    `usgMammaeImage6` TEXT NULL,
    `usgMammaeLaporan` TEXT NULL,
    `usgMammaeKesimpulan` TEXT NULL,
    `framinghamScore` TEXT NULL,
    `kesimpulanTesPsikologi` TEXT NULL,
    `kesimpulan` TEXT NULL,
    `saran` TEXT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_roleId_fkey` FOREIGN KEY (`roleId`) REFERENCES `Role`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `Company`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Patient` ADD CONSTRAINT `Patient_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `Company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `McuResult` ADD CONSTRAINT `McuResult_patientId_fkey` FOREIGN KEY (`patientId`) REFERENCES `Patient`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
