-- AlterTable
ALTER TABLE `McuResult` MODIFY `rontgenImage` MEDIUMTEXT NULL,
    MODIFY `ekgImage1` MEDIUMTEXT NULL,
    MODIFY `ekgImage2` MEDIUMTEXT NULL,
    MODIFY `ekgImage3` MEDIUMTEXT NULL,
    MODIFY `treadmillImage1` MEDIUMTEXT NULL,
    MODIFY `treadmillImage2` MEDIUMTEXT NULL,
    MODIFY `treadmillImage3` MEDIUMTEXT NULL,
    MODIFY `spirometryImage` MEDIUMTEXT NULL,
    MODIFY `usgAbdomenImage1` MEDIUMTEXT NULL,
    MODIFY `usgAbdomenImage2` MEDIUMTEXT NULL,
    MODIFY `usgAbdomenImage3` MEDIUMTEXT NULL,
    MODIFY `usgAbdomenImage4` MEDIUMTEXT NULL,
    MODIFY `usgAbdomenImage5` MEDIUMTEXT NULL,
    MODIFY `usgAbdomenImage6` MEDIUMTEXT NULL,
    MODIFY `usgMammaeImage1` MEDIUMTEXT NULL,
    MODIFY `usgMammaeImage2` MEDIUMTEXT NULL,
    MODIFY `usgMammaeImage3` MEDIUMTEXT NULL,
    MODIFY `usgMammaeImage4` MEDIUMTEXT NULL,
    MODIFY `usgMammaeImage5` MEDIUMTEXT NULL,
    MODIFY `usgMammaeImage6` MEDIUMTEXT NULL,
    MODIFY `treadmillImage4` MEDIUMTEXT NULL;
