-- AlterTable
ALTER TABLE `McuResult` ADD COLUMN `audiometriValidatorName` VARCHAR(191) NULL,
    ADD COLUMN `audiometriValidatorQr` TEXT NULL,
    ADD COLUMN `conclusionValidatorName` VARCHAR(191) NULL,
    ADD COLUMN `conclusionValidatorQr` TEXT NULL,
    ADD COLUMN `ekgValidatorName` VARCHAR(191) NULL,
    ADD COLUMN `ekgValidatorQr` TEXT NULL,
    ADD COLUMN `hematologiValidatorName` VARCHAR(191) NULL,
    ADD COLUMN `hematologiValidatorQr` TEXT NULL,
    ADD COLUMN `kimiaDarahValidatorName` VARCHAR(191) NULL,
    ADD COLUMN `kimiaDarahValidatorQr` TEXT NULL,
    ADD COLUMN `rontgenValidatorName` VARCHAR(191) NULL,
    ADD COLUMN `rontgenValidatorQr` TEXT NULL,
    ADD COLUMN `spirometriValidatorName` VARCHAR(191) NULL,
    ADD COLUMN `spirometriValidatorQr` TEXT NULL,
    ADD COLUMN `urinalisaValidatorName` VARCHAR(191) NULL,
    ADD COLUMN `urinalisaValidatorQr` TEXT NULL,
    ADD COLUMN `usgAbdomenValidatorName` VARCHAR(191) NULL,
    ADD COLUMN `usgAbdomenValidatorQr` TEXT NULL,
    ADD COLUMN `usgMammaeValidatorName` VARCHAR(191) NULL,
    ADD COLUMN `usgMammaeValidatorQr` TEXT NULL;
